import React from 'react'
import Header from '../common/Header';
import Footer from '../common/Footer';
 


const SellerPolicy = () => {
    return (
        <div className='bg-light'>
            <Header />
            <div className='container mt-5'>
                <div className='row'>
                    <div className='col-12 col-md-4 d-flex align-items-center mt-md-5 pt-md-5 h-100'><img src="https://kewlmotors.com/wp-content/uploads/2021/06/about-kewl-motors.png" alt="logo" className=' img-fluid' /></div>
                    <div className='col-12 col-md-8'>
                        <h1 className='mt-3 fw-bold'>VENDOR POLICY</h1>
                        <hr className='border border-5 border-secondary' />
                        <p className='text-justify'>
                            This document is an electronic record published in accordance with the provisions of the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 as amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        <p>
                            This policy (“Vendor Policy”) along with the Privacy Policy(hyperlink) together constitute a legally binding agreement (this “Agreement”) between SpareTrade India Private Limited, a private limited company duly incorporated in accordance with the provisions of the Companies Act, 2013 (herein referred to as “Company”, “Our”, “We”, “Us”) and the vendor (“Vendor”, “You”, “Your”) with respect to Your use of Our Platform and Services.
                        </p>
                        <p>
                            1.BACKGROUND
                        </p>
                        <p>
                            1.1.The Platform is owned by the Company and operates as an online e-commerce marketplace for the display, advertising and sale of Products by various Vendors to the end customers (“Customers/Users”) and provides related services to the Vendors and to the Customers/Users of the Platform. We shall act as Vendor’s service provider for providing various services in relation to the sale of its Products, and the use of the Platform for enabling promotion/advertisement of the its Products (“Services”).
                        </p>
                        <p>
                            2.YOUR APPROVAL
                        </p>
                        <p>
                            2.1.You may accept this Vendor Policy only if:
                        </p>
                        <p>
                            (a)You are a natural Person, are of the legal age, eligibility and mental capability to form a binding contract.
                        </p>
                        <p>
                            (b)You are a juristic Person, are lawfully existing and have all the authorizations, permits and allowances to enter into this Vendor Policy and form a binding contract.
                        </p>
                        <p>
                            (c)You are not legally barred or restricted from accessing the Platform or using the Services or any part of it.
                        </p>
                        <p>
                            2.2.We do not want any Person to access the Services if such Person does not understand, approve of or accept each and every term specified in this Vendor Policy. Hence, You are requested to read this Vendor Policy carefully and understand it before approving, accepting and agreeing to be bound by it.
                        </p>
                        <p>
                            3.PRODUCTS
                        </p>
                        <p>
                            3.1.The Vendor shall offer its Products to Us for the purposes of sale on the Platform. Based on market analysis conducted by Us, We may make recommendations to the Vendor from time to time on the specific Products and the quantities thereof, from the entire range/collection that are to be displayed, advertised and offered for sale by the Vendor through the Platform. The Vendor shall make its final decision on the Products and their quantities to be displayed on the Platform on the basis of such recommendations. Notwithstanding the foregoing, the Company has the right to refuse to display, or withdraw from the Platform, any Product for sale on the Platform.
                        </p>
                        <p>
                            3.2.The Products offered for sale by the Vendor are either manufactured by the Vendor or are sourced/ purchased by the Vendor from third party suppliers/manufacturers (“Suppliers”). In the event a Vendor purchases Products from a Supplier, the Vendor shall furnish to Us, a ‘no objection certificate’ from the Supplier of the Products in the format provided in ANNEXURE A of this Vendor Policy.
                        </p>
                        <p>
                            4.SERVICES TO BE PROVIDED BY US
                        </p>
                        <p>
                            4.1.In order to enable the sale and promotion of the Products of the Vendor, We shall carry out the following functions for and on behalf of the Vendor for consideration-
                        </p>
                        <p>
                            4.1.1.The Vendor authorizes Us to provide to the Customers/Users of the Platform:
                        </p>
                        <p>
                            (a)information and assistance in relation to the listed Products and sales thereof.
                        </p>
                        <p>
                            (b)information in relation to status of the order placed by Customers. and
                        </p>
                        <p>
                            (c)operating a customer helpdesk for other inquiries in relation to Products and orders, customer complaints and grievances.
                        </p>
                        <p>
                            4.1.2.The Vendor authorizes Us to place on the Platform:
                        </p>
                        <p>
                            (a)a description of the Vendor (including but not limited to name and place of Vendor’s business).
                        </p>
                        <p>
                            (b)description of each of its Products (including but not limited to the technical description of the Products, brand name of the Product, the price of the Product and any applicable warranty terms) on the Platform.
                        </p>
                        <p>
                            (c)Product rating based on Customer reviews.
                        </p>
                        <p>
                            4.1.3.The Vendor agrees and undertakes to fully co-operate with Us as reasonably required, in connection with any customer-service functions undertaken by Us.
                        </p>
                        <p>
                            4.1.4.The Vendor acknowledges that We may offer end of season sale discounts or such other discounts as We may deem fit on the Platform. Such discounts shall be borne by the Vendor and the Company in a ratio as mutually decided between the Vendor and the Company.
                        </p>
                        <p>
                            4.2.Ordering, Packaging and Delivery
                        </p>
                        <p>
                            4.2.1.The Platform will enable Customers to place orders for the Product(s) they wish to purchase, which shall be notified to both the Company and the Vendor simultaneously.
                        </p>
                        <p>
                            4.2.2.The Vendor hereby irrevocably confirms that upon receiving the confirmation of the order by the Customer in respect of any Product, We shall be entitled to, and be deemed to have been authorized by the Vendor, to collect directly or through its nominees or third-party service providers, the relevant Product(s) from the Vendor for the purposes of delivering to the Customer on behalf the Vendor, within 24 (twenty-four) hours of the confirmed order being received on the Platform.
                        </p>
                        <p>
                            4.2.3.In case the Vendor fails to prepare the Product or does not have the Product in required condition, the Vendor shall be penalised by the Company in accordance with Clause 12 of this Vendor Policy.
                        </p>
                        <p>
                            4.2.4.The Vendor shall ensure to provide all relevant authorisations in favour of the Company to facilitate aforesaid collection of the relevant Products from the Vendor.
                        </p>
                        <p>
                            4.2.5.The Vendor shall (either itself or through its Suppliers) be responsible for warranty relating to the Products as per its standard product warranty and shall keep the Company fully indemnified in this regard.
                        </p>
                        <p>
                            5.REFUND AND RETURN POLICY
                        </p>
                        <p>
                            5.1.The Vendor agrees to offer return/replacement of Products ordered by Customers on the Platform within 2 days of such return/replacement request. However, for Products which cannot be returned/replaced, the Vendor is required to inform Us or provide a list of such Products beforehand.
                        </p>
                        <p>
                            5.2.In order to fulfil a return/replacement request, Our third-party service provider will pick-up the Product(s) from the Customer and deliver it directly to the Vendor. Upon receiving such Product(s), the Vendor shall carry out a quality check of the Product(s) within 24 hours of receiving the Product(s). After a quality check is completed, the Vendor shall inform Us whether the Product has cleared the quality check or not, so we can initiate the refund.
                        </p>
                        <p>
                            5.3.In case of a replacement request, once the returned Product(s) passes the quality check, the new Product as ordered by the Customer shall be delivered in the manner as specified under Clause 4.2.2 of this Vendor Policy.
                        </p>
                        <p>
                            5.4.Vendor agrees to offer refunds for Products sold during an offer or a scheme.
                        </p>
                        <p>
                            5.5.In case a Customer complaint that a defected/different Product is received, the Vendor shall be solely responsible for any discrepancies that may arise due to such default and shall also bear any additional costs incurred by Us or Our third-party service providers to resolve such complaint of the Customer.
                        </p>
                        <p>
                            6.LICENSE TO MAKE USE OF INTELLECTUAL PROPERTY
                        </p>
                        <p>
                            6.1.The Vendor hereby grants to the Company, a royalty free irrevocable license to use its Intellectual Property for the purposes of providing the Services by Us as contemplated hereunder.
                        </p>
                        <p>
                            6.2.In the event, the Vendor sources the Products from any Supplier, the Vendor shall obtain all applicable licenses and consents for the use of such Supplier’s Intellectual Property in connection with the Product being sourced from such Supplier for the purposes of providing the Services by Us, prior to the display of such Products on the Platform. In the event We receive a claim and/or notice from a Supplier of products regarding infringement of its intellectual property rights, We shall forward such claim to the Vendor and the Vendor shall be liable to defend such claims and keep Us harmless and indemnified against the same. We may also provide all necessary information regarding the Vendor to any such party from whom a genuine claim has been received by Us and the Vendor shall have no objection to the same. We may further take any other appropriate legal action against the Vendor, as it may deem fit, in this regard.
                        </p>
                        <p>
                            6.3.It is hereby clarified that no rights in the Intellectual Property of the Vendor or the Suppliers are granted in favour of Us except the limited license to use the Intellectual Property for the purposes of providing the Services by Us.
                        </p>
                        <p>
                            6.4.The term “Intellectual Property” shall mean and include logos, trade names, brand names, trademarks, copyrights and other relevant intellectual property rights relevant to the advertisement and sale of the Products.
                        </p>
                        <p>
                            7.TITLE AND RISK IN RELATION TO THE PRODUCTS
                        </p>
                        <p>
                            7.1.No risk or title to the Products shall pass to the Company or its third-party service providers at any point of time for any reason whatsoever. The title and risks to the Products shall be deemed to pass directly from the Vendor to the Customer upon delivery of the Products to the Customer and payment of the consideration for the Products by the Customer.
                        </p>
                        <p>
                            7.2.Notwithstanding anything to the contrary contained herein, it is clarified and agreed that any and all liabilities arising in connection with any defect, fault or shortcoming in the Product(s) shall be of the Vendor or its Supplier alone and this provision shall survive the termination of this Vendor Policy.
                        </p>
                        <p>
                            8.TERM AND TERMINATION
                        </p>
                        <p>
                            8.1.You will bound by this Vendor Policy from the date You commence using Our Platform for selling Your Products till this Vendor Policy is terminated either by Us or You in accordance with below Clause 8.2.
                        </p>
                        <p>
                            8.2.This Vendor Policy may be terminated by:
                        </p>
                        <p>
                            8.2.1.Company:
                        </p>
                        <p>
                            (a)On a breach of this Vendor Policy by the Vendor, if such breach is not cured within 30 (thirty) days of receipt of notification from the Company.
                        </p>
                        <p>
                            (b)On a breach of this Vendor Policy by Vendor and which, in the reasonable opinion of Us, is not capable of cure. In such a case, We shall not be obliged to provide a chance to cure the breach but shall be entitled to terminate this Vendor Policy forthwith.
                        </p>
                        <p>
                            (c)In case We reasonably believe that the Vendor’s actions or omissions have prejudicially affected the reputation of the Company and/or the Platform; or required to terminate this Vendor Policy in accordance with applicable Law, Government order or order of a court with requisite jurisdiction.
                        </p>
                        <p>
                            8.2.2.Vendor:
                        </p>
                        <p>
                            (a)By giving one month’s prior notice in writing to Us.
                        </p>
                        <p>
                            8.3.Upon termination of this Vendor Policy:
                        </p>
                        <p>
                            8.3.1.We shall be entitled to remove the Products of the Vendor displayed on the Platform and/or advertised on the Platform.
                        </p>
                        <p>
                            8.3.2.All orders in relation to the Products of the Vendor that have been received prior to the termination of this Vendor Policy and all obligations to return the Product and/or refund the amount paid by the Customer which may arise in the period after the date of termination hereof, shall be honoured and completed, notwithstanding any termination hereof, in accordance with the terms of this Vendor Policy; and the Vendor agrees and undertakes to co-operate with Us for the same.
                        </p>
                        <p>
                            8.3.3.The Vendor shall forthwith without delay or demur make payment of all outstanding amounts that are due to Us under this Vendor Policy, including any amount refunded by Us to the Customer after the termination, which shall be paid by the Vendor to Us immediately upon receipt of any demand from Us in this regard.
                        </p>
                        <p>
                            8.3.4.We shall within 30 days of the date of termination, make payment of all outstanding amounts that are due to the Vendor in accordance with the terms of this Vendor Policy.
                        </p>
                        <p>
                            9.REPRESENTATIONS AND WARRANTIES OF THE VENDOR
                        </p>
                        <p>
                            9.1.The Vendor has all rights (including all Intellectual Property rights), approvals and consents from any third parties (including Suppliers) required to enter into and perform this Vendor Policy and to supply and sell the Products as contemplated hereunder.
                        </p>
                        <p>
                            9.2.The Vendor has procured all necessary registrations/permits as required under applicable Laws for sale of Products through the Platform (including without limitation registration under applicable Laws pertaining to sales tax and GST of the relevant states). The Vendor further represents that the Vendor shall be solely responsible for collection and payment of applicable taxes with respect to the sale of the Products to the relevant government authorities in a timely manner and We shall not be responsible nor held liable for any non-compliance/contravention of applicable Laws by the Vendor. The Vendor hereby agrees to keep Us harmless and indemnified in this regard. The indemnity obligations of the Vendor contained herein shall survive the termination of this Vendor Policy.
                        </p>
                        <p>
                            9.3.All the Products are genuine, merchantable, marketable and of the quality and nature as described by the Vendor to Us and displayed on the Platform. The Products are genuine, new and are not counterfeit products.
                        </p>
                        <p>
                            9.4.The Vendor may add link of the Company with text “Find us on SpareTrade Store” on their website/ blog.
                        </p>
                        <p>
                            9.5.Further, the Vendor agrees and undertakes that it shall not provide photographs/images of Products for display, upload, modify, publish, transmit, update or share any information or share/list(s) any information relating to the Product that:
                        </p>
                        <p>
                            (a)Is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever.
                        </p>
                        <p>
                            (b)harm minors in any way.
                        </p>
                        <p>
                            (c)infringes any patent, trademark, copyright or other proprietary rights.
                        </p>
                        <p>
                            (d)violates any Law for the time being in force.
                        </p>
                        <p>
                            (e)deceives or misleads the addressee about the origin of such messages.
                        </p>
                        <p>
                            (f)communicates any information which is grossly offensive or menacing in nature.
                        </p>
                        <p>
                            (g)impersonate another person.
                        </p>
                        <p>
                            (h)contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of the Platform. or
                        </p>
                        <p>
                            (i)threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.
                        </p>
                        <p>
                            10.INDEMNITY
                        </p>
                        <p>
                            10.1.The Vendor shall promptly on demand indemnify and hold harmless the Company and its officers, directors, employees and agents for and against all liabilities, costs and expenses (including reasonable attorney’s fees) incurred or suffered, or to be incurred or suffered, by Us that arise out of or in any way relate to, or result from any breach by the Vendor of any of the provisions of this Vendor Policy (including, without limitation, any of the representations or warranties of the Vendor set forth herein), or negligence, fraud or wilful misconduct of the Vendor, or any claim, demand, suit, action or proceeding brought by a third party that involves, relates to or concerns a violation or other breach by the Vendor of any of the provisions of this Vendor Policy.
                        </p>
                        <p>
                            11.PENALTY
                        </p>
                        <p>
                            11.1.In the event of non-adherence of this Vendor Policy by the Vendor resulting into the occurrence of either of the following instances shall attract a penalty of such an amount as the Company may deem fit basis the Product in question (with an upper limit of 30% of the Product price in question) per instance:
                        </p>
                        <p>
                            (a)Inability to meet the orders, whether due to inadequacy of stocks or otherwise, in which case the penalty shall be per order.
                        </p>
                        <p>
                            (b)Returns due to bad/defective/wrong Product.
                        </p>
                        <p>
                            (c)Any loss occurred due to discrepancies with respect to the logistics.
                        </p>
                        <p>
                            (d)Delay in packing the order for delivery.
                        </p>
                        <p>
                            12.GOVERNING LAW AND JURISDICTION
                        </p>
                        <p>
                            12.1.This Vendor Policy shall be governed by and shall be construed in accordance with the laws of India. All disputes relating to this Vendor Policy shall be settled in the courts located at Uttar Pradesh, India.
                        </p>
                        <p>
                            13.MISCELLANIOUS
                        </p>
                        <p>
                            13.1.Confidentiality: You may be given and have access to confidential and proprietary information of the other Vendors and Users pursuant to Services provided under this Vendor Policy. You will not use any such confidential information for Your own corporate purposes or any other purpose (except as contemplated under this Vendor Policy) without a prior written consent of the Person owning such information and shall use their best efforts to keep confidential and not to disclose to any Person any such confidential and proprietary information, except as mutually agreed or required by applicable Law.
                        </p>
                        <p>
                            13.2.Display Association: We shall have a right to display and publicize Our association with You, other Vendors and the Services We have provided to Our Users, in Our collateral and branding materials.
                        </p>
                        <p>
                            13.3.Severability: If any provision of this Vendor Policy is determined to be unenforceable then such provision shall, to that extent, be deemed deleted from this Vendor Policy and the legality, validity and enforceability of the remaining provisions of this Vendor Policy shall not be in any way affected. Any act of either Us or the Vendor, done prior to the provisions being held unenforceable shall be deemed to be valid and binding on the other.
                        </p>
                        <p>
                            13.4.Waiver: Waiver by Us of any one default of any one Vendor will not waive subsequent defaults of the same or different kind, by the same or different Vendor, and no failure or delay of Us to exercise or enforce any of its rights hereunder shall act as a waiver of those rights.
                        </p>
                        <p>
                            13.5.Assignment: You will not assign or transfer any of your rights or liabilities under this Vendor Policy to any other Person. We may freely assign Our rights and benefits (in full or in part) under this Vendor Policy to any Person. You acknowledge that We have a right (but not the obligation) to deliver the Services either ourselves, or, through Our affiliates or any third parties.
                        </p>
                        <p>
                            13.6.Notices: We may post notices within the Platform or send You notices on the registered e-mail address or the telephone numbers shared with Us. You will deemed to have received such notices, if sent via e-mail, within 24 hours of Us sending the notice. Your use of Services after expiry of 3 days from the day notice was sent, shall constitute receipt and acceptance of the notices sent to You.
                        </p>
                        <p>
                            13.7.Non-compete and Non-solicit: You will not, directly or indirectly, (i) solicit or attempt to solicit, induce or recruit, engage or in any other way encourage Our employees, consultants or Users to terminate their respective engagements with Us and/ or engage with You and/ or any third party; or (ii) engage in any activity which is same or similar to the Platform or the Services.
                        </p>
                        <p>
                            13.8.Force Majeure: We will not be liable for any failure or delay in the performance of this Vendor Policy due to reasons beyond Our reasonable control, including but not limited to, acts of war, epidemic/pandemic, acts of God, earthquake, flood, riot, embargo, sabotage, Governmental act or failure of the internet.
                        </p>
                        <p>
                            13.9.Modification: We reserve the right, at any time, to add to, change, update, or modify this Vendor Policy. Upon any such modification, We will endeavour to inform You of any changes incorporated in this Vendor Policy.
                        </p>
                        <p>
                            14.CONTACT US
                        </p>
                        <p>
                            14.1.You can reach our customer support team to address any of your queries at <span className='text-primary'>cs@SpareTrade.store </span>.
                        </p>
                        <p>
                            15.DEFINITIONS AND INTERPRETATION
                        </p>
                        <p>
                            15.1.All the capitalized terms contained in this Vendor Policy that have not been defined elsewhere, shall mean as follows:
                        </p>
                        (a)“Government” or “Governmental Authority”, for the purposes of this Vendor Policy, means any statutory authority, Government department, agency, commission, board, tribunal, court, or other entity in India, or abroad, as applicable, authorized to make Laws.
                        <p>
                            (b)“Law” or “Laws” includes all applicable statutes, enactments, acts of legislature or parliament, laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives, and orders of any Government Authority, tribunal, board or court, in India or abroad, as applicable.
                        </p>
                        <p>
                            (c)“Person” shall mean any natural person, limited or unlimited liability company, corporation, partnership (whether limited or unlimited), proprietorship, Hindu undivided family, trust, union, association, government or any agency or political subdivision thereof or any other entity that may be treated as a person under applicable law.
                        </p>
                        <p>
                            (d)“Platform” shall mean the website (<span className='text-primary'>https://www.SpareTrade.store</span>) and the application (whether android or IOS) downloadable from third party service providers, including any updates thereof, as We may provide from time to time.
                        </p>
                        <p>
                            (e)“Products” shall mean, with respect to a Vendor, such goods as the Vendor displays, markets, sells and/ or attempts to sell through the Platform.
                        </p>
                        <p>
                            15.2.Any reference to the singular includes a reference to the plural and vice versa; any reference to one gender includes a reference to the other gender(s), unless explicitly stated otherwise.
                        </p>
                        <p>
                            15.3.Headings and captions are used for convenience only and not for interpretation of the Vendor Policy.
                        </p>
                        <p>
                            15.4.Any reference to a natural Person shall, include his/ her heirs, executors and permitted assignees and any reference to a juristic Person shall, include its affiliates, successors and permitted assignees, unless repugnant to the context.
                        </p>
                      

                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}
export default SellerPolicy;