import React from 'react'
import Header from '../common/Header';
import Footer from '../common/Footer';
 
 

const TermOfUse = () => {
  return (
    <div className='bg-light'>
      <Header />
      <div className='container mt-5'>
        <div className='row'>
          <div className='col-12 col-md-4 d-flex align-items-center mt-md-5 pt-md-5 h-100'><img src="https://kewlmotors.com/wp-content/uploads/2021/06/about-kewl-motors.png" alt="logo" className=' img-fluid' /></div>
          <div className='col-12 col-md-8'>
            <h1 className='mt-3 fw-bold'>CUSTOMER TERMS OF USE AND SERVICE</h1>
            <hr className='border border-5 border-secondary' />
            <p className='text-justify'>
            This document is an electronic record published in accordance with the provisions of the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 as amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
    <p>
    These customer terms of use and service (“Customer Terms”) along with the Privacy Policy (hyperlink) together constitute a legally binding agreement (this “Customer Agreement”) between SpareTrade India Private Limited, a private limited company duly incorporated in accordance with the provisions of the Companies Act, (herein referred to as “Company”, “Our”, “We”, “Us”) and you, the customer (“Customer”, “You”, “Your”) with respect to Your use of Our Platform and Services.
    </p>
          <p>
          1.YOUR APPROVAL
            </p>  
            <p>
            1.1.You may accept this Customer Agreement only if:

            </p>
            <p>
            (a)You are a natural Person, are of the legal age, eligibility, and mental capability to form a binding contract
            </p>
            <p>
            (b)You are a juristic Person, are lawfully existing and have all the authorizations, permits and allowances to enter into this Customer Agreement and form a binding contract. 
            </p>
            <p>
            (c)You are not legally barred or restricted from accessing the Platform or using the Services or any part of it.
            </p>
            <p>
            1.1.1.1.2.We do not want any Person to access the Services if such Person does not understand, approve of or accept each and every term specified in this Customer Agreement. Hence, You are requested to read these Customer Terms and Privacy Policy carefully and understand the Customer Agreement before approving, accepting and agreeing to be bound by it.
            </p>
            <p>
            1.3.You will be deemed to have accepted this Customer Agreement by simply availing Services, including but not limited to, by:

            </p>
            <p>
            (a)creating a Registered Account; and
            </p>
            <p>
            (b)using the Services via the Platform.

            </p>
            <p>
            2.PROVISION OF SERVICES
            </p>
            <p>
            1.2.2.1.Services provided to You are subject to Your acceptance and approval of this Customer Agreement. You are requested not to use and/ or access the Platform, Services and/ or any part thereof if You do not approve of, agree with and accept each and every term of this Customer Agreement. 
            </p>
            <p>
            2.2.The purpose of Services is to provide an e-commerce Platform for purchasing and selling of various Products listed on the Platform.
            </p>
            <p>
            2.3.In order to avail Services, We require You to register on the Platform by providing specific information, including but not limited to, name, email ID, phone number, current location (city & state), and creating an account (“Registered Account”). You agree and understand that Services shall not be provided to You unless You register on the Platform in the form and manner required by Us. Unless You have created a Registered Account on the Platform, You can only use the Platform to explore the Products listed and cannot place an order to purchase them or add them to cart. 
            </p>
            <p>
            2.4.Subject to applicable Law, We may stop provision of Services (or any part of Services), permanently or temporarily, to You or may modify or change the nature of Services and/ or these Customer Terms at Our sole discretion, without any prior notice to You. Your Use of Services following any such modification shall constitute Your deemed acceptance of this Customer Agreement (or as it may be modified).
            </p>
            <p>
            3.USE OF SERVICES
            </p>
            <p>
            3.1.In order to use Services, You will require accessing the Platform through internet in such form and manner as provided by Us. We may update the Platform from time to time in order to ensure a better experience for the Customers and consequently may temporarily cut or restrict Your access to the Platform or the Services.

            </p>
            <p>
            3.2.You agree to use the Platform and Services only for such purposes as is permitted by this Customer Agreement.
            </p>
            <p>
            1.2.3.3.1.3.2.3.3.You will solely be responsible for maintaining the privacy and confidentiality of Your access details (user ID, password etc.) with respect to Your Registered Account. Any access to or use of Your Registered Account shall be construed as access or use of such Registered Account by You.
            </p>
            <p>
            3.4.You agree not to impersonate another Person or impersonate, guide or host on behalf of, or falsely state or otherwise misrepresent Your affiliation with any Person, including, but not limited to other Customers, Us and/ or Our officials, employees, Vendors, agents, partners, affiliates, dealers and/ or franchisees.
            </p>
            <p>
            3.5.Unless agreed to the contrary in writing, Services provided by Us are for non-commercial and personal use of the Users only. Users are not allowed to copy, reproduce, alter, modify, create derivative works of, or publicly display any Services or any part thereof as their services.
            </p>
            <p>
            3.6.E-Commerce Platform for selling and purchasing of Products: 
            </p>
            <p>
            1.2.3.3.1.3.2.3.3.3.4.3.5.3.6.3.6.1.Through the Platform, We facilitate the purchase of Products offered for sale by Vendors. The Products and information displayed on the Platform is an "invitation to offer" to public at large. Your order for purchase constitutes Your "offer" which shall be subject to acceptance or rejection by Us and shall further subject to these Customer Terms. All accepted offers shall be fulfilled by Us. If You have provided your valid email address or contact number, We may notify You by email or through SMS (as the case may be) as soon as possible to confirm receipt of Your order. You understand and agree all items offered for sale on the Platform, and the Content made available by the Vendors, are third party user generated Contents and third-party Products. The authenticity and genuineness of the Products made available by the Vendors through the Platform shall be the sole responsibility of the Vendors. You understand and agree that We shall have no liability with respect to the authenticity of the Products being facilitated through the Platform.
            </p>
            <p>
            3.6.2.You agree and acknowledge that the Vendors shall be solely responsible for any claim/ liability/ damages that may arise in the event it is discovered that such Vendor do not have the sole and exclusive legal ownership over the Products that have been offered for sale on the Platform by such Vendor, or did not have the absolute right, title and authority to deal in and offer for sale such Products on the Platform. 
            </p>
            <p>
            3.6.3.We reserve the right, with or without notice, to cancel or reduce the quantity of any Products to be provided to You that We believe, in our sole discretion, may result in the violation of this Customer Agreement or any applicable Law. 
            </p>
            <p>
            3.6.5.We reserve the right to change, suspend, or discontinue the availability of any of the Products at any time, without any notice or liability. You acknowledge that the price payable in connection with the Product, may be subject to change, without notice or liability.
            </p>
            <p>
            3.6.6.While describing Our Products on Our Platform, We endeavour to be as accurate as possible. To the extent implied by applicable Law, We do not warrant that the Product descriptions, colours, information or other Content available on the Platform are accurate, complete, reliable, current, or error-free. The Platform may contain typographical errors or inaccuracies and may not be complete or updated. Such errors, inaccuracies or omissions may also relate to pricing and availability of the Product. Please note that the Product pictures are indicative and may not match the actual Product.

            </p>
            <p>
            3.6.7.Delivery: You understand that We may take third-party services to deliver Products to You. Upon placing an order, You will receive an estimated time of delivery. However, the estimated delivery times are indicative, hence there may be some unforeseeable delays, which are beyond Our control. Further, You agree and acknowledge that the third-party delivery partners are not associated with Us, and that We shall not be held responsible for any loss/ damage/ liability caused to You due to any act/omission/commission of such third-party delivery partner. 
            </p>
            <p>

            3.6.8.Cancellation: You agree and acknowledge that You will have the right to cancel an ordered Product only until the order is picked by Our third-party delivery agent. No cancellation shall be accepted after the order has been picked for delivery. In case You fail to cancel the order and do not accept it once Our delivery agent reaches Your premises with the order, You shall be charged for the same before You are able to place Your next order through Our Platform. You agree that We shall not be liable to pay for any damage or loss either direct or indirect owing to such cancellation of the order or delay in delivery.
            </p>
            <p>
            3.6.9.Customer Feedback: The Platform provides to You an option to provide Your feedback on the Services and/or Products offered by Us. You agree and acknowledge that You shall not upload any Content on the Platform which:
            </p>
            <p>
            (a)is/might be defamatory, obscene, pornographic, vulgar, offensive or against the public policy; 
            </p>
            <p>
            (b)promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group;
            </p>
            <p>
            (c)is/might be violent or threatening or promotes violence or actions that are threatening to any Person; 

            </p>
            <p>
            (d)harms minors in any way;
            </p>
            <p>
            (e)promotes illegal or harmful activities or substances; 
            </p>
            <p>
            (f)violates any guidelines or terms of this Customer Agreement or any applicable Laws.
1.2.3.3.1.3.2.3.3.3.4.3.5.3.6.3.6.1.3.6.2.3.6.3.3.6.4.3.6.5.3.6.6.3.6.7.
4.RESTRICTIONS ON USE OF SERVICES
            </p>
            <p>
            4.1.You agree that You will not use the Services for any purpose that is illegal, unlawful, or prohibited by this Customer Agreement. You will not attempt to engage or engage in any activity that may:
            </p>
            <p>
            (a)reverse engineer, decompile or otherwise extract the source code(s) related to the Platform or Services or any part thereof, unless it is expressly permitted by Us in writing or is required by applicable Law;
            </p>
            <p>
            (b)use any robot, spider, retrieval application, or other device to retrieve or index any portion of the Platform, Services or Content;
            </p>
            <p>
            (c)collect information about other Customers, Vendors in any illegal or unlawful manner for any illegal or unlawful purposes;
            </p>
            <p>
            (d)register on the Platform to access Services or create any Registered Accounts by automated means or under false or fraudulent pretences for using the Services;
            </p>
            <p>
            (e)transmit any viruses, worms, defects, trojan horses, or any items of a destructive nature through the use of Platform or Services;
            </p>
            <p>
            (f)use Services in any manner that can damage, disable, overburden, or impair, or undertake any action which is harmful or potentially harmful to, any of the servers, networks, computer systems or resources connected to any of the servers connected, directly or indirectly to the Services, or interfere with any other third party's access to and/or enjoyment of Services;
            </p>
            <p>
            (g)carry out any denial of service or any other harmful attacks on the Platform or; disrupt or place unreasonable burdens or excessive loads on, or interfere with or attempt to make, or attempt any unauthorized access to the Services or any part of Services or any Customer; or
            </p>
            <p>
            (h)forge headers or otherwise manipulate identifiers in order to disguise the origin of any part of the Platform or any Content transmitted through the Platform.
            </p>
            <p>
            1.2.3.4.4.1.4.2.You will not circumvent or disable any digital rights management, usage rules, or other security features of the Platform; remove, alter, or obscure any proprietary notices (including copyright notices) on any portion of the Platform; and not use Services in any manner that threatens or is likely to threaten the integrity, performance or availability of Services to You or to other Customers generally.
            </p>
            <p>
            5.PAYMENT TERMS
            </p>
            <p>
            5.1.To the extent permitted by applicable Law, You acknowledge and agree that We may use certain third-party vendors and service providers, including payment gateways, to process payments and manage payment card information. 
            </p>
            <p>
            5.2.In order to make payments online, You undertake to use a valid payment card or bank details or third party wallets or details required for any other mode of payment (“Payment Details”) with the authority to use the same, to have sufficient funds or credit available to complete the payment on the Platform in good standing. By providing the Payment Details, You represent, warrant, and covenant that: (a) You are legally authorized to provide such Payment Details; (b) You are legally authorized to perform payments using such Payment Details; and (c) such action does not violate the terms and conditions applicable to Your use of such Payment Details or applicable Law. You agree that You are responsible for any fees charged by Your mobile carrier in connection with Your use of the payment services through Your mobile. You may add, delete, and edit the Payment Details You have provided from time to time through the Platform.
            </p>
            <p>
            5.3.Except to the extent otherwise required by applicable Law, We are not/shall not be liable for any payments authorized through the Platform using Your Payment Details. Particularly, the Company is not liable for any payments that do not complete because: (a) Your payment card or bank account or third party wallet does not contain sufficient funds to complete the transaction or the transaction exceeds the credit limit in respect of the Payment Details provided; (b) You have not provided Us with correct Payment Details; (c) Your payment card has expired; or (d) circumstances beyond the Our control (such as, but not limited to, power outages, interruptions of cellular service, or any other interference from an outside force) prevent the execution of the transaction.
            </p>
            <p>
            5.4.We may from time to time provide certain Users with promotional offers and discounts that may result in different amounts charged for the same or similar Products obtained through the use of the Services, and You agree that such promotional offers and discounts, unless also made available to You, shall have no bearing on Your use of the Services. 
            </p>
            <p>
            5.5.The Company may do such checks as it deems fit before approving the receipt of/Your commitment to pay (for cash on delivery transactions) transaction price from You for security or other reasons at the discretion of the Company. As a result of such check if We are not satisfied with Your creditability or genuineness of the transaction or other reasons at Our sole discretion, We shall have the right to reject the receipt of/ Your commitment to pay transaction price. For avoidance of doubt, it is hereby clarified that the ‘cash on delivery’ feature for payment, may be disabled for certain Customers, at the sole discretion of the Company.
            </p>
            <p>
            5.6.We may delay notifying the payment confirmation, if We suspect that You are conducting high transaction volumes, to ensure safety of the transaction and transaction price. In addition, We may hold transaction price and may not dispatch or remit transaction price to law enforcement officials (instead of refunding the same to You) at the request of law enforcement officials or in the event You are engaged in any form of illegal activity.
            </p>
            <p>
            6.REFUND AND RETURN POLICY
            </p>
            <p>
            6.1.We offer return/replacement of only such Products which are either received in a damaged state or do not match with the ordered Product. In either of these cases, You must contact Us via email ID (provided below) within 5 (five) days of receipt of such Product, so We can arrange for a replacement or a refund, as requested by You. We will arrange a replacement or bear the cost of shipping the item(s) back to Us, in case of a return.
            </p>
            <p>
            6.2.A replacement shall be subject to the availability of the same Product with Us. We might deny Your request of replacement if We do not have the stock of the Product so replaced. The number of days within which the replaced Product shall be delivered to You will depend upon its availability at that point in time. 
            </p>
            <p>
            6.3.In case of a return/replacement due to receipt of damaged Product, We may ask You to send Us an unboxing video to ensure that the Product was received in a damaged state.
            </p>
            <p>
            6.4.In order to return/replace a Product, You must ensure that the Product is not used by You and is preserved in its original condition, tags, and packaging.  
            </p>
            <p>
            6.5.We may refuse a refund/replacement request if We find evidence of fraud, refund abuse or other manipulative behaviour that entitles Us to a claim against You.
            </p>
            <p>
            6.6.Except for cash on delivery transaction, refund, if any, shall be made at the same issuing bank from where transaction price was received, or through any other method available on the Platform, as chosen by You. For cash on delivery transactions, refunds, if any, will be made via electronic payment transfers. 
            </p>
            <p>
            6.7.For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved by Reserve Bank India. Refunds may be supported for selected banks. Where a bank is not supported for processing refunds, You will be required to share alternate bank account details with Us for processing the refund. 
            </p>
            <p>
            6.8.Please further note that You shall be completely responsible for providing correct bank details and We and/or any third-party payment gateway used by Us shall not be responsible in case wrong information has been provided to by You.
            </p>
            <p>
            6.9.You agree and acknowledge that while collecting the returned/replaced order from You, Our delivery agent shall first send a real-time picture of the Product to the Vendor, in order to ensure the quality and physical state of the Product. In case the Vendor does not approve the quality and/or physical state of the Product, the delivery agent shall return back the product to You and Your request for replacement/return shall stand to be cancelled. 
            </p>
            <p>
            7.INTELLECTUAL PROPERTY RIGHTS AND DATA OWNERSHIP
            </p>
            <p>
            7.1.Use of Services shall, at all times, be governed by and subject to the applicable Laws regarding copyright, trademark, patent, and trade secret ownership and use of intellectual property and You agree to abide by such Laws. You shall solely be responsible for any violation of any Law or for any infringement of any intellectual property rights caused pursuant to Your use of Services.
            </p>
            <p>
            7.2.When You upload, submit, store or send any Content on the Platform, You give Us a non-exclusive, perpetual, irrevocable, royalty-free, sub-licensable, worldwide right and license to use, copy, transmit, host, store, reproduce, modify, create derivative works of, communicate, publish, publicly perform, publicly display, print, edit, translate, reformat and distribute any Content, in whole or in part for the purpose of providing, operating, promoting, and/ or improving the Platform and/ or Services and for business of Us.
            </p>
            <p>
            7.3.You acknowledge that certain underlying technology or software used by Us in connection with Services and certain Content displayed on Platform may contain rights of other Users or a third party and for use any such third party’s intellectual property, You may need to get permission directly from the owner of such intellectual property. 
            </p>
            <p>
            7.4.All third parties owning any intellectual property have a right to take appropriate actions against any Customer for any violation, infringement or passing off by such Customer. We respect the intellectual property rights of all Persons and do not hold any responsibility for any violations of any intellectual property rights by You or other Customers. 
            </p>
            <p>
            8.PRIVACY
            </p>
            <p>
            8.1.Our Privacy Policy explains how We treat Your data and protect Your privacy when You use the Services. By using the Services, You agree to Our use of Your data according to the Privacy Policy.
            </p>
            <p>
            8.2.You are responsible for maintaining the confidentiality of passwords associated with any device or online accounts that You use to access the Services or any part thereof. You are solely responsible for all activities that occur with use of Your Registered Account or device. If You become aware of any unauthorized use of Your Registered Account or device, then You may immediately notify Us and the relevant authorities.
            </p>
            <p>
            9.TERM AND TERMINATION
            </p>
            <p>
            9.1.You are bound by the Customer Agreement from the time You commence using the Services till earlier of (i) when You cease access or use to Services in any manner, including deleting Your Registered Account; or (ii) Us terminating this Customer Agreement with respect to You by permanently barring Your access to Services.

            </p>
            <p>
            9.2.We reserve the right to terminate Your access to Services or any part of Services, at any time if:
            </p>
            <p>
            (a)You knowingly or unknowingly cause, direct or indirect, breach, as ascertained by Us, of any part of this Customer Agreement;
            </p>
            <p>
            (b)You do not make the requisite payments with respect to any Product purchased by You via Our Platform; 

            </p>
            <p>
            (c)a third party with which We offers Services, has terminated its relationship with Us or ceased to offer the related services to Us or to You;
            </p>
            <p>
            (d)provision of Services or any part of Services is no longer commercially viable or feasible for Us;
            </p>
            <p>
            (e)We believe that You are a repeat infringer of the terms of this Customer Agreement or You are in violation of applicable Law; or
            </p>
            <p>
            (f)We are required to terminate this Customer Agreement by applicable Law, Government order or order of a court with requisite jurisdiction.
            </p>
            <p>
            1.2.3.4.5.6.7.8.9.9.1.9.2.9.3.Upon termination of this Customer Agreement, all the legal rights, obligations and liabilities that You and Us have benefited from, been subject to (or which have accrued over time whilst this Customer Agreement was in force or which are expressed to continue indefinitely, shall be unaffected by this cessation, and shall continue to apply to such rights, obligations and liabilities indefinitely.
            </p>
            <p>
            10.LIMITATION OF LIABILITY 
            </p>
            <p>
            10.1.Use of Services by You is entirely at Your own risk and We shall not be liable for any direct, indirect, incidental, consequential, special, exemplary, punitive, monetary or any other damages, fees, fines, penalties or liabilities whatsoever arising out of or relating to any Customer’s use of Services or accessing the Platform.
            </p>
            <p>
            10.2.Provision of the Services does not constitute an institution of agency between Us and any of Our Customers. Our relationship with each and every individual Customer shall be on a principal-to-principal basis only. You are solely responsible for any breach of Your obligations under this Customer Agreement, applicable Law and/ or the consequences of any such breach.
            </p>
            <p>
            10.3.We will not be liable for any acts or omissions of any third party, including but not limited to the Vendors and delivery agents, or for any unauthorized interception of the Platform or Services or any breach of this Customer Agreement attributable in full or in part to the acts or omissions of third parties, or damages associated with features that We do not furnish, or damages that result from the operation systems, equipment, facilities or services provided by third parties to You.
            </p>
            <p>
            10.4.The Platform may include/ display links to other online platforms which are outside Our control and may contain materials that are objectionable, unlawful or inaccurate. We do not endorse or support such third-party links or the products and/ or services they provide, hence, We shall not be responsible or liable for the Content, accuracy or authenticity of such third party links.
            </p>
            <p>
            11.REPRESENTATIONS, WARRANTIES AND COVENANTS
            </p>
            <p>
            11.1.You represent and warrant that: (i) You are lawfully existing under applicable Laws and have full power and authority to enter into, execute and deliver this Customer Agreement; (ii) You have all necessary and valid authorizations required for performance of Your obligations under this Customer Agreement; (iii) this Customer Agreement constitutes a legal, valid and binding obligation on You, enforceable against You; (iv) You have accepted this Customer Agreement relying on Your own business judgment and You have not been induced by any Person; and (v) execution, delivery and performance of this Customer Agreement by You shall not (a) violate any provision of the territorial and/ or jurisdictional Laws applicable to You; (b) conflict with or result in material breach or violation of any terms, or constitute default under, any other agreement by which You are bound; (c) violate any order, judgment or decree against, or binding upon, Your; or (d) violate any Law or regulation of India or any other country in which You maintains Your principal office (in case You are a corporate Person) or of which You are a citizen and a resident (in case You are a natural Person).
            </p>
            <p>
            11.2.We disclaim all warranties in relation to access to or provision of Platform or Services, whether express or implied, including but not limited to:
            </p>
            <p>
            (a)Services being constantly available or available at all;
            </p>
            <p>
            (b)Services being successfully executed in all cases; 
            </p>
            <p>
            (c)Services being always functional without any disruption, delay or error;
            </p>
            <p>
            (d)Customer’s ability to use the Services, directly or indirectly;
            </p>
            <p>
            (e)Customers’ satisfaction with the Services;
            </p>
            <p>
            (f)the accuracy of the data provided in the course of Service; 
            </p>
            <p>
            (g)that all bugs or errors in relation to Services will be fixed or corrected;
            </p>
            <p>
            (h)that Platform will be compatible with all devices, all networks and all browsers; 
            </p>
            <p>

(i)that use of Services is fit for a particular purpose or use, except as provided herein; or
            </p>
            <p>
            (j)that Services is accessible in every location.

            </p>
            <p>
            1.2.3.4.5.6.7.8.9.10.11.11.1.11.2.11.3.Customers shall defend, indemnify and hold Us, and Our officers, directors, employees, representatives, consultants and agents harmless from and against any third party claims, actions, demands, liabilities, judgments, and settlements, including without limitation, any loss or damage suffered by Us (including loss of reputation and/ or goodwill) and including reasonable legal fee that may result from or alleged to result from (a) such Customer’s unauthorized, illegal and/ or unlawful access to or use of the Services; (b) such Customer’s breach of any rules, regulations and/ or orders under any applicable Law; and (c) such Customer’s breach of any obligation under this Customer Agreement.
            </p>
            <p>
            11.4.You expressly represent and warrant that You will not use Services if You do not understand, agree to become a party to and abide by all the terms specified of this Customer Agreement. Any violation of this Customer Agreement by You may result in legal liability upon You and nothing in this Customer Agreement shall be deemed to confer any rights to any third party or any other Person, not expressly granted such rights herein.
            </p>
            <p>
            12.GOVERNING LAW AND JURISDICTION
            </p>
            <p>
            12.1.This Customer Agreement shall be governed by and shall be construed in accordance with the laws of India. All disputes relating to this Customer Agreement shall be settled in the courts located at Uttar Pradesh, India.
            </p>
            <p>
            13.MISCELLANIOUS
            </p>
            <p>
            13.1.Confidentiality: You may be given and have access to confidential and proprietary information of the other users pursuant to Services provided under this Customer Agreement. You will not use any such confidential information for Your own corporate purposes or any other purpose (except as contemplated under this Customer Agreement) without a prior written consent of the Person owning such information and shall use their best efforts to keep confidential and not to disclose to any Person any such confidential and proprietary information, except as mutually agreed or required by applicable Law.
            </p>
            <p>
            13.2.Severability: If any provision of this Customer Agreement is determined to be unenforceable then such provision shall, to that extent, be deemed deleted from this Customer Agreement and the legality, validity and enforceability of the remaining provisions of this Customer Agreement shall not be in any way affected. Any act of either Us or the Customer, done prior to the provisions being held unenforceable shall be deemed to be valid and binding on the other.
            </p>
            <p>
            13.3.Waiver: Waiver by Us of any one default of any one Customer will not waive subsequent defaults of the same or different kind, by the same or different Customer, and no failure or delay of Us to exercise or enforce any of its rights hereunder shall act as a waiver of those rights. 
            </p>
            <p>
            13.4.Assignment: While the Customers shall not assign or transfer any of their rights or liabilities under this Agreement to any other Person, We may freely assign Our rights and benefits (in full or in part) under this Agreement to any Person. You acknowledge that We have a right (but not the obligation) to deliver the Services either ourselves, or, through Our affiliates or any third parties.
            </p>
            <p>
            13.5.Notices: We may post notices within the Platform or send You notices on the registered e-mail address or the telephone numbers shared with Us. You will deemed to have received such notices, if sent via e-mail, within 24 (twenty-four) hours of Us sending the notice. Your use of Services after expiry of 3 (three) days from the day notice was sent, shall constitute receipt and acceptance of the notices sent to You.
            </p>
            <p>
            13.6.Non-compete and Non-solicit: You will not, directly or indirectly, (i) solicit or attempt to solicit, induce or recruit, engage or in any other way encourage Our employees, consultants, Vendors, delivery agents or Customer to terminate their respective engagements with Us and/ or engage with You and/ or any third party; or (ii) engage in any activity which is same or similar to the Platform or the Services.
            </p>
            <p>
            13.7.Force Majeure: We will not be liable for any failure or delay in the performance of this Customer Agreement due to reasons beyond Our reasonable control, including acts of war, epidemic/pandemic, acts of God, earthquake, flood, riot, embargo, sabotage, Governmental act or failure of the internet.
            </p>
            <p>
            14.DISCLAIMERS
            </p>
            <p>
            14.1.The information, software, products, and services forming parts of the Services have been contributed by various users and may include inaccuracies or typographical errors. Any advice received or inferred via the Services should not be relied upon by the Customers for any personal, legal or financial decisions and Customers should consult an appropriate professional for tailored advice, specific to their situation.
            </p>
            <p>
            14.2.We reserve the right, at any time, to add to, change, update, or modify this Customer Agreement so please review it frequently. We will endeavour to inform You of any changes incorporated in this Customer Agreement that are significant (in Our opinion), however, You are requested to regularly visit and review this page.
            </p>
            <p>
            14.3.EXCEPT AS EXPRESSLY PROVIDED IN THIS CUSTOMER AGREEMENT AND TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED “AS IS” AND WE DO NOT MAKE WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING THOSE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OR ANY REPRESENTATIONS REGARDING AVAILABILITY, RELIABILITY, OR ACCURACY OF PLATFORM, SERVICES AND/ OR GOODS AND/ OR SERVICES PROMOTED AND/ OR OFFERED THROUGH THE PLATFORM OR SERVICES.

            </p>
            <p>
            15.CUSTOMER SUPPORT
            </p>
            <p>
            15.1.Customer Support: You can reach our customer support team to address any of your queries at <span className='text-primary'>cs@SpareTrade.store</span>

            </p>
            <p>
            16.DEFINITIONS AND INTERPRETATION
            </p>
            <p>
            16.1.All the capitalized terms contained in this Customer Agreement that have not been defined elsewhere, shall mean as follows:
            </p>
            <p>
            (a)“Content’’ shall mean and include any audio, video, visual, graphic, text content or combination thereof, including messages, information, articles, description of Products, images, videos, GIFs, reviews, ratings, comments, queries or any other like material, created and/ or added on the Platform, by Us, Vendor or by a Customer.
            </p>
            <p>
            (b)“Government” or “Governmental Authority”, for the purposes of this Customer Agreement, means any statutory authority, Government department, agency, commission, board, tribunal, court, or other entity in India, or abroad, as applicable, authorized to make Laws.
            </p>
            <p>
            (c)“Law” or “Laws” includes all applicable statutes, enactments, acts of legislature or parliament, laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives, and orders of any Government Authority, tribunal, board or court, in India or abroad, as applicable.
            </p>
            <p>
            (d)“Person” shall mean any natural person, limited or unlimited liability company, corporation, partnership (whether limited or unlimited), proprietorship, Hindu undivided family, trust, union, association, government or any agency or political subdivision thereof or any other entity that may be treated as a person under applicable Law.
            </p>
            <p>

            (e)“Platform” shall mean the website (<span className='text-primary'>https://www.SpareTrade.store</span>) and the application (whether android or IOS) downloadable from third party service providers, including any updates thereof, as We may provide from time to time.

            </p>
            <p>
            (f)“Products” shall mean and include such goods as We display, market, sell and/ or attempt to sell through the Platform.

            </p>
            <p>
            (g)“Services” shall mean and include the service of browsing and/or purchasing Products via the Platform
            </p>
            <p>
            (h)“Vendor” shall mean such User of the Platform which/ who displays, markets, sells, and/ or attempts to sell certain Products through the Platform.
            </p>
            <p>
            1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.16.1.16.2.Any reference to the singular includes a reference to the plural and vice versa; any reference to one gender includes a reference to the other gender(s), unless explicitly stated otherwise.
            </p>
            <p>
            16.3.Headings and captions are used for convenience only and not for interpretation of the Customer Agreement.
            </p>
            <p>
            16.4.Any reference to a natural Person shall, include his/her heirs, executors and permitted assignees and any reference to a juristic Person shall, include its affiliates, successors and permitted assignees, unless repugnant to the context.
            </p>
        </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}
export default TermOfUse;